#!/usr/bin/env python3
"""Diagnostic A: wall ice mass budget for a single solved case.

Loads a per-case ``.npz`` produced by ``run_pipeline.py`` (which carries the
``t, h, w, v, r`` time series), integrates the wall condensation and frictional
melt over the last diurnal cycle, and writes the net ice-accumulation profile
plus a plot.

Usage
-----
    python run_wall_budget.py --case results/wmin0.050_ratio1.3.npz \
                              --config config/run_config.yaml

Older case files that predate the ``v`` field can be regenerated by re-running
the pipeline, or pass ``--no-melt`` to skip the (usually small) melt term.
"""

from __future__ import annotations

import argparse
import logging
import os

import numpy as np

from enceladus_plume.config import load_config
from enceladus_plume.wall_budget import wall_mass_budget

logger = logging.getLogger("wall_budget")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--case", required=True, help="per-case .npz from run_pipeline.py")
    ap.add_argument("--config", default=None, help="YAML config (defaults to package default)")
    ap.add_argument("--Tb", type=float, default=272.6, help="base temperature (K)")
    ap.add_argument("--n-z", type=int, default=800, help="wall grid resolution")
    ap.add_argument("--out", default=None, help="output .npz (default: <case>_wallbudget.npz)")
    ap.add_argument("--no-plot", action="store_true")
    ap.add_argument("-v", "--verbose", action="store_true")
    args = ap.parse_args()

    logging.basicConfig(level=logging.INFO if args.verbose else logging.WARNING,
                        format="%(message)s")

    cfg = load_config(args.config)
    data = np.load(args.case)
    for key in ("t", "h", "w", "v", "r"):
        if key not in data:
            raise SystemExit(
                f"case file {args.case!r} is missing '{key}'. Re-run the pipeline "
                f"(it now saves the velocity series) or use an updated case file.")

    res = wall_mass_budget(
        data["t"], data["h"], data["w"], data["v"], data["r"],
        cfg, Tb=args.Tb, n_z=args.n_z)

    print(res.summary())

    out = args.out or (os.path.splitext(args.case)[0] + "_wallbudget.npz")
    np.savez(out, zeta=res.zeta, deposition=res.deposition, melt=res.melt,
             net_sigma=res.net_sigma, net_thickness=res.net_thickness,
             L=res.L, D=res.D, rho_ice=res.rho_ice,
             healing_cycles=res.healing_cycles, healing_years=res.healing_years)
    logger.info("wrote %s", out)

    if not args.no_plot:
        _plot(res, os.path.splitext(out)[0] + ".png")


def _plot(res, path: str) -> None:
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except Exception as exc:  # pragma: no cover
        logger.warning("plotting skipped (%s)", exc)
        return

    fig, axes = plt.subplots(1, 2, figsize=(11, 5), sharey=True)
    # depth below surface for the y-axis (0 at surface, increasing downward)
    below = res.surface - res.zeta
    axes[0].plot(res.deposition, below, label="condensation (gain)", color="C0")
    axes[0].plot(-res.melt, below, label="friction melt (loss)", color="C3")
    axes[0].axhline(res.D, ls=":", color="grey", label="equilibrium water level")
    axes[0].set_xlabel("ice change per cycle [kg/m$^2$]")
    axes[0].set_ylabel("depth below surface [m]")
    axes[0].legend(fontsize=8)
    axes[0].set_title("Wall ice budget")

    axes[1].plot(res.net_thickness * 1e3, below, color="k")
    axes[1].axvline(0.0, ls=":", color="grey")
    axes[1].set_xlabel("net thickness change [mm/cycle]")
    axes[1].set_title("Net (deposition $-$ melt)")

    for ax in axes:
        ax.set_ylim(res.surface, 0)  # surface at top
        ax.set_yscale("symlog")
    fig.suptitle(f"healing: {res.healing_cycles:.2e} cycles "
                 f"({res.healing_years:.2e} yr)")
    fig.tight_layout()
    fig.savefig(path, dpi=130)
    logger.info("wrote %s", path)


if __name__ == "__main__":
    main()
